// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-KQt9HXvBbtJyLXrXoSZBvPyVvF063uI',
    appId: '1:803796815257:web:3bec403d51a3374c219708',
    messagingSenderId: '803796815257',
    projectId: 'connectu-bedb3',
    authDomain: 'connectu-bedb3.firebaseapp.com',
    storageBucket: 'connectu-bedb3.appspot.com',
    measurementId: 'G-B4LE3MY5ZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZWGbGeD_EK1d_dvSnOVWUNrA20kA8ypQ',
    appId: '1:803796815257:android:383b4d204a1c1a7e219708',
    messagingSenderId: '803796815257',
    projectId: 'connectu-bedb3',
    storageBucket: 'connectu-bedb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5kUeqBPt3-HStH_M7qAUJKbf1jHloRhs',
    appId: '1:803796815257:ios:cd2bda1616d66c0f219708',
    messagingSenderId: '803796815257',
    projectId: 'connectu-bedb3',
    storageBucket: 'connectu-bedb3.appspot.com',
    iosClientId: '803796815257-jcc0n7dsmpt6qnaseaofr87dp6i4ags7.apps.googleusercontent.com',
    iosBundleId: 'com.example.contentu',
  );
}
